create extension if not exists pgcrypto;

create table if not exists public.access_passwords (
    level text primary key check (level in ('family', 'party', 'admin')),
    password_hash text not null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.access_sessions (
    token_hash text primary key,
    access_level text not null check (access_level in ('family', 'party', 'admin')),
    expires_at timestamptz not null,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.guests (
    id bigint generated by default as identity primary key,
    full_name text not null,
    email text,
    group_id text not null,
    is_primary boolean not null default false,
    is_plus_one boolean not null default false,
    notes text,
    rsvp_status text not null default 'pending' check (rsvp_status in ('pending', 'accepted', 'declined')),
    meal_choice text,
    dietary_notes text,
    address_line1 text,
    address_line2 text,
    city text,
    state text,
    postal_code text,
    last_rsvp_at timestamptz,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists guests_group_id_idx on public.guests (group_id);
create index if not exists guests_full_name_idx on public.guests using gin (to_tsvector('simple', coalesce(full_name, '')));

create table if not exists public.rsvp_submissions (
    id bigint generated by default as identity primary key,
    group_id text,
    submitter_name text not null,
    submitter_email text,
    attending boolean not null,
    guest_count integer not null default 1,
    meal_choice text,
    dietary_notes text,
    special_message text,
    song_request text,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.address_submissions (
    id bigint generated by default as identity primary key,
    full_name text not null,
    email text,
    street text,
    street2 text,
    city text,
    state text,
    zip text,
    submitted_at timestamptz not null default timezone('utc', now()),
    raw_payload jsonb not null default '{}'::jsonb
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists access_passwords_set_updated_at on public.access_passwords;
create trigger access_passwords_set_updated_at
before update on public.access_passwords
for each row execute function public.set_updated_at();

drop trigger if exists guests_set_updated_at on public.guests;
create trigger guests_set_updated_at
before update on public.guests
for each row execute function public.set_updated_at();

create or replace function public.access_rank(level text)
returns integer
language sql
immutable
as $$
    select case lower(coalesce(level, ''))
        when 'family' then 1
        when 'party' then 2
        when 'admin' then 3
        else 0
    end;
$$;

create or replace function public.require_session(session_token text, required_level text default 'family')
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
    session_level text;
begin
    delete from public.access_sessions where expires_at <= timezone('utc', now());

    select access_level
    into session_level
    from public.access_sessions
    where token_hash = encode(digest(coalesce(session_token, ''), 'sha256'), 'hex')
      and expires_at > timezone('utc', now())
    limit 1;

    if session_level is null then
        raise exception 'Unauthorized';
    end if;

    if public.access_rank(session_level) < public.access_rank(required_level) then
        raise exception 'Forbidden';
    end if;

    return session_level;
end;
$$;

create or replace function public.login_access(candidate_password text, session_ttl_ms bigint default 3600000)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    matched_level text;
    raw_token text;
begin
    select level
    into matched_level
    from public.access_passwords
    where crypt(coalesce(candidate_password, ''), password_hash) = password_hash
    order by public.access_rank(level) desc
    limit 1;

    if matched_level is null then
        raise exception 'Invalid password.';
    end if;

    raw_token := encode(gen_random_bytes(32), 'hex');

    insert into public.access_sessions (token_hash, access_level, expires_at)
    values (
        encode(digest(raw_token, 'sha256'), 'hex'),
        matched_level,
        timezone('utc', now()) + make_interval(secs => greatest(session_ttl_ms, 60000) / 1000)
    );

    return jsonb_build_object(
        'success', true,
        'token', raw_token,
        'accessLevel', matched_level,
        'expiresIn', greatest(session_ttl_ms, 60000)
    );
end;
$$;

create or replace function public.get_access_session(session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    session_level text;
    session_expiry timestamptz;
    expires_in_ms bigint;
begin
    select access_level, expires_at
    into session_level, session_expiry
    from public.access_sessions
    where token_hash = encode(digest(coalesce(session_token, ''), 'sha256'), 'hex')
      and expires_at > timezone('utc', now())
    limit 1;

    if session_level is null then
        raise exception 'Unauthorized';
    end if;

    expires_in_ms := greatest(0, floor(extract(epoch from (session_expiry - timezone('utc', now()))) * 1000));

    return jsonb_build_object(
        'success', true,
        'accessLevel', session_level,
        'expiresIn', expires_in_ms
    );
end;
$$;

create or replace function public.logout_access(session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
    delete from public.access_sessions
    where token_hash = encode(digest(coalesce(session_token, ''), 'sha256'), 'hex');

    return jsonb_build_object('success', true);
end;
$$;

create or replace function public.search_guest_groups(search_name text, max_results integer default 5)
returns jsonb
language sql
security definer
set search_path = public
as $$
with tokens as (
    select regexp_split_to_array(trim(coalesce(search_name, '')), '\s+') as parts
), filtered as (
    select g.*
    from public.guests g, tokens t
    where cardinality(t.parts) >= 2
      and lower(g.full_name) like '%' || lower(t.parts[1]) || '%'
      and lower(g.full_name) like '%' || lower(t.parts[cardinality(t.parts)]) || '%'
), grouped as (
    select distinct group_id
    from filtered
    order by group_id
    limit greatest(coalesce(max_results, 5), 1)
)
select coalesce(jsonb_agg(
    jsonb_build_object(
        'groupId', grp.group_id,
        'primaryGuest', coalesce((
            select full_name
            from public.guests
            where group_id = grp.group_id
            order by is_primary desc, full_name asc
            limit 1
        ), ''),
        'guests', coalesce((
            select jsonb_agg(jsonb_build_object(
                'id', guest.id,
                'fullName', guest.full_name,
                'email', guest.email,
                'isPrimary', guest.is_primary,
                'isPlusOne', guest.is_plus_one,
                'notes', guest.notes,
                'rsvpStatus', guest.rsvp_status,
                'mealChoice', guest.meal_choice,
                'dietaryNotes', guest.dietary_notes,
                'addressLine1', guest.address_line1,
                'addressLine2', guest.address_line2,
                'city', guest.city,
                'state', guest.state,
                'postalCode', guest.postal_code
            ) order by guest.is_primary desc, guest.full_name asc)
            from public.guests guest
            where guest.group_id = grp.group_id
        ), '[]'::jsonb)
    )
), '[]'::jsonb)
from grouped grp;
$$;

create or replace function public.submit_rsvp(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    submitter_name text := trim(coalesce(payload->>'name', payload->>'rsvpName', ''));
    submitter_email text := trim(coalesce(payload->>'email', payload->>'rsvpEmail', ''));
    guest_group_id text := nullif(trim(coalesce(payload->>'guestGroupId', '')), '');
    normalized_dietary text := nullif(trim(coalesce(payload->>'dietaryRestrictions', '')), '');
    normalized_message text := nullif(trim(coalesce(payload->>'specialMessage', '')), '');
    normalized_song_request text := nullif(trim(coalesce(payload->>'songRequest', '')), '');
    normalized_meal_choice text := nullif(trim(coalesce(payload->>'mealChoice', '')), '');
    guest_responses jsonb := coalesce(payload->'guestResponses', '[]'::jsonb);
    accepted_count integer := 0;
    attending_flag boolean := false;
begin
    if submitter_name = '' then
        raise exception 'RSVP name is required.';
    end if;

    if submitter_email = '' then
        raise exception 'RSVP email is required.';
    end if;

    if guest_group_id is null and jsonb_array_length(guest_responses) > 0 then
        raise exception 'guestGroupId is required when submitting per-guest responses.';
    end if;

    select count(*) filter (where lower(coalesce(entry.value->>'status', '')) = 'accepted')
    into accepted_count
    from jsonb_array_elements(guest_responses) as entry(value);

    attending_flag := accepted_count > 0 or lower(coalesce(payload->>'attending', '')) in ('yes', 'true');

    insert into public.rsvp_submissions (
        group_id,
        submitter_name,
        submitter_email,
        attending,
        guest_count,
        meal_choice,
        dietary_notes,
        special_message,
        song_request
    ) values (
        guest_group_id,
        submitter_name,
        submitter_email,
        attending_flag,
        greatest(coalesce(nullif(payload->>'guestCount', '')::integer, accepted_count, 1), 1),
        normalized_meal_choice,
        normalized_dietary,
        coalesce(normalized_message, normalized_song_request),
        normalized_song_request
    );

    if jsonb_array_length(guest_responses) > 0 then
        update public.guests guest
        set rsvp_status = case lower(coalesce(entry.value->>'status', ''))
                when 'accepted' then 'accepted'
                when 'declined' then 'declined'
                else guest.rsvp_status
            end,
            meal_choice = coalesce(nullif(trim(coalesce(entry.value->>'mealChoice', '')), ''), guest.meal_choice),
            full_name = coalesce(nullif(trim(coalesce(entry.value->>'name', '')), ''), guest.full_name),
            last_rsvp_at = timezone('utc', now()),
            updated_at = timezone('utc', now())
        from jsonb_array_elements(guest_responses) as entry(value)
        where guest.id = nullif(entry.value->>'guestId', '')::bigint
          and guest.group_id = guest_group_id;
    elsif guest_group_id is not null then
        update public.guests
        set rsvp_status = case when attending_flag then 'accepted' else 'declined' end,
            meal_choice = coalesce(normalized_meal_choice, meal_choice),
            last_rsvp_at = timezone('utc', now()),
            updated_at = timezone('utc', now())
        where group_id = guest_group_id;
    end if;

    if guest_group_id is not null and normalized_dietary is not null then
        update public.guests
        set dietary_notes = normalized_dietary,
            updated_at = timezone('utc', now())
        where group_id = guest_group_id;
    end if;

    return jsonb_build_object(
        'success', true,
        'status', case when attending_flag then 'accepted' else 'declined' end,
        'message', case when attending_flag
            then 'Thank you for your RSVP! We cannot wait to celebrate with you.'
            else 'We appreciate the update and will miss you at the celebration.'
        end
    );
end;
$$;

create or replace function public.save_address_submission(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.address_submissions (
        full_name,
        email,
        street,
        street2,
        city,
        state,
        zip,
        raw_payload
    ) values (
        trim(coalesce(payload->>'fullName', '')),
        nullif(trim(coalesce(payload->>'email', '')), ''),
        nullif(trim(coalesce(payload->>'street', '')), ''),
        nullif(trim(coalesce(payload->>'street2', '')), ''),
        nullif(trim(coalesce(payload->>'city', '')), ''),
        nullif(trim(coalesce(payload->>'state', '')), ''),
        nullif(trim(coalesce(payload->>'zip', '')), ''),
        coalesce(payload, '{}'::jsonb)
    );

    return jsonb_build_object('success', true, 'message', 'Thank you! Your address has been saved.');
end;
$$;

create or replace function public.list_admin_guests(session_token text)
returns jsonb
language sql
security definer
set search_path = public
as $$
    with authorized as (
        select public.require_session(session_token, 'admin')
    )
    select coalesce(jsonb_agg(jsonb_build_object(
        'id', guest.id,
        'fullName', guest.full_name,
        'email', guest.email,
        'groupId', guest.group_id,
        'isPrimary', guest.is_primary,
        'isPlusOne', guest.is_plus_one,
        'notes', guest.notes,
        'rsvpStatus', guest.rsvp_status,
        'mealChoice', guest.meal_choice,
        'dietaryNotes', guest.dietary_notes,
        'addressLine1', guest.address_line1,
        'addressLine2', guest.address_line2,
        'city', guest.city,
        'state', guest.state,
        'postalCode', guest.postal_code,
        'lastRsvpAt', guest.last_rsvp_at
    ) order by guest.group_id, guest.is_primary desc, guest.full_name asc), '[]'::jsonb)
    from public.guests guest, authorized;
$$;

create or replace function public.admin_upsert_guest(session_token text, guest_id bigint, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    saved_id bigint;
begin
    perform public.require_session(session_token, 'admin');

    if trim(coalesce(payload->>'fullName', '')) = '' or trim(coalesce(payload->>'groupId', '')) = '' then
        raise exception 'fullName and groupId are required.';
    end if;

    if guest_id is null then
        insert into public.guests (
            full_name,
            email,
            group_id,
            is_primary,
            is_plus_one,
            notes,
            rsvp_status,
            meal_choice,
            dietary_notes,
            address_line1,
            address_line2,
            city,
            state,
            postal_code
        ) values (
            trim(payload->>'fullName'),
            nullif(trim(coalesce(payload->>'email', '')), ''),
            trim(payload->>'groupId'),
            coalesce((payload->>'isPrimary')::boolean, false),
            coalesce((payload->>'isPlusOne')::boolean, false),
            nullif(trim(coalesce(payload->>'notes', '')), ''),
            coalesce(nullif(trim(coalesce(payload->>'rsvpStatus', '')), ''), 'pending'),
            nullif(trim(coalesce(payload->>'mealChoice', '')), ''),
            nullif(trim(coalesce(payload->>'dietaryNotes', '')), ''),
            nullif(trim(coalesce(payload->>'addressLine1', '')), ''),
            nullif(trim(coalesce(payload->>'addressLine2', '')), ''),
            nullif(trim(coalesce(payload->>'city', '')), ''),
            nullif(trim(coalesce(payload->>'state', '')), ''),
            nullif(trim(coalesce(payload->>'postalCode', '')), '')
        ) returning id into saved_id;
    else
        update public.guests
        set full_name = trim(payload->>'fullName'),
            email = nullif(trim(coalesce(payload->>'email', '')), ''),
            group_id = trim(payload->>'groupId'),
            is_primary = coalesce((payload->>'isPrimary')::boolean, false),
            is_plus_one = coalesce((payload->>'isPlusOne')::boolean, false),
            notes = nullif(trim(coalesce(payload->>'notes', '')), ''),
            rsvp_status = coalesce(nullif(trim(coalesce(payload->>'rsvpStatus', '')), ''), 'pending'),
            meal_choice = nullif(trim(coalesce(payload->>'mealChoice', '')), ''),
            dietary_notes = nullif(trim(coalesce(payload->>'dietaryNotes', '')), ''),
            address_line1 = nullif(trim(coalesce(payload->>'addressLine1', '')), ''),
            address_line2 = nullif(trim(coalesce(payload->>'addressLine2', '')), ''),
            city = nullif(trim(coalesce(payload->>'city', '')), ''),
            state = nullif(trim(coalesce(payload->>'state', '')), ''),
            postal_code = nullif(trim(coalesce(payload->>'postalCode', '')), ''),
            updated_at = timezone('utc', now())
        where id = guest_id
        returning id into saved_id;

        if saved_id is null then
            raise exception 'Guest not found.';
        end if;
    end if;

    return jsonb_build_object('success', true, 'id', saved_id);
end;
$$;

create or replace function public.admin_delete_guest(session_token text, guest_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
    perform public.require_session(session_token, 'admin');
    delete from public.guests where id = guest_id;
    return jsonb_build_object('success', true);
end;
$$;

create or replace function public.admin_import_guests(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    entry jsonb;
    inserted_count integer := 0;
begin
    perform public.require_session(session_token, 'admin');

    for entry in select value from jsonb_array_elements(coalesce(payload, '[]'::jsonb))
    loop
        if trim(coalesce(entry->>'fullName', '')) = '' or trim(coalesce(entry->>'groupId', '')) = '' then
            continue;
        end if;

        insert into public.guests (
            full_name,
            email,
            group_id,
            is_primary,
            is_plus_one,
            notes,
            rsvp_status,
            meal_choice,
            dietary_notes,
            address_line1,
            address_line2,
            city,
            state,
            postal_code
        ) values (
            trim(entry->>'fullName'),
            nullif(trim(coalesce(entry->>'email', '')), ''),
            trim(entry->>'groupId'),
            coalesce((entry->>'isPrimary')::boolean, false),
            coalesce((entry->>'isPlusOne')::boolean, false),
            nullif(trim(coalesce(entry->>'notes', '')), ''),
            coalesce(nullif(trim(coalesce(entry->>'rsvpStatus', '')), ''), 'pending'),
            nullif(trim(coalesce(entry->>'mealChoice', '')), ''),
            nullif(trim(coalesce(entry->>'dietaryNotes', '')), ''),
            nullif(trim(coalesce(entry->>'addressLine1', '')), ''),
            nullif(trim(coalesce(entry->>'addressLine2', '')), ''),
            nullif(trim(coalesce(entry->>'city', '')), ''),
            nullif(trim(coalesce(entry->>'state', '')), ''),
            nullif(trim(coalesce(entry->>'postalCode', '')), '')
        );

        inserted_count := inserted_count + 1;
    end loop;

    return jsonb_build_object('success', true, 'inserted', inserted_count);
end;
$$;

alter table public.access_passwords enable row level security;
alter table public.access_sessions enable row level security;
alter table public.guests enable row level security;
alter table public.rsvp_submissions enable row level security;
alter table public.address_submissions enable row level security;

revoke all on public.access_passwords from anon, authenticated;
revoke all on public.access_sessions from anon, authenticated;
revoke all on public.guests from anon, authenticated;
revoke all on public.rsvp_submissions from anon, authenticated;
revoke all on public.address_submissions from anon, authenticated;

grant execute on function public.login_access(text, bigint) to anon, authenticated;
grant execute on function public.get_access_session(text) to anon, authenticated;
grant execute on function public.logout_access(text) to anon, authenticated;
grant execute on function public.search_guest_groups(text, integer) to anon, authenticated;
grant execute on function public.submit_rsvp(jsonb) to anon, authenticated;
grant execute on function public.save_address_submission(jsonb) to anon, authenticated;
grant execute on function public.list_admin_guests(text) to anon, authenticated;
grant execute on function public.admin_upsert_guest(text, bigint, jsonb) to anon, authenticated;
grant execute on function public.admin_delete_guest(text, bigint) to anon, authenticated;
grant execute on function public.admin_import_guests(text, jsonb) to anon, authenticated;
