create extension if not exists pgcrypto;

create table if not exists public.access_passwords (
    level text primary key check (level in ('family', 'party', 'admin')),
    password_hash text not null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.access_sessions (
    token_hash text primary key,
    access_level text not null check (access_level in ('family', 'party', 'admin')),
    expires_at timestamptz not null,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.guests (
    id bigint generated by default as identity primary key,
    full_name text not null,
    email text,
    group_id text not null,
    is_primary boolean not null default false,
    is_plus_one boolean not null default false,
    is_hmu_eligible boolean not null default false,
    notes text,
    rsvp_status text not null default 'pending' check (rsvp_status in ('pending', 'accepted', 'declined')),
    hmu_selection text not null default 'not_selected',
    meal_choice text,
    dietary_notes text,
    address_line1 text,
    address_line2 text,
    city text,
    state text,
    postal_code text,
    last_rsvp_at timestamptz,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

alter table public.guests
    add column if not exists is_child boolean not null default false;

alter table public.guests
    add column if not exists is_hmu_eligible boolean not null default false,
    add column if not exists hmu_selection text not null default 'not_selected';

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'guests_hmu_selection_check'
    ) then
        alter table public.guests
            add constraint guests_hmu_selection_check
            check (hmu_selection in ('not_selected', 'hair', 'makeup', 'hair_makeup', 'opt_out'));
    end if;
end;
$$;

create index if not exists guests_group_id_idx on public.guests (group_id);
create index if not exists guests_full_name_idx on public.guests using gin (to_tsvector('simple', coalesce(full_name, '')));

create table if not exists public.menu_items (
    id bigint generated by default as identity primary key,
    name text not null unique,
    is_child_meal boolean not null default false,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

insert into public.menu_items (name, is_child_meal, sort_order, is_active)
values
    ('Gnocchi', false, 10, true),
    ('Atlantic Salmon', false, 20, true),
    ('Flank Steak', false, 30, true),
    ('Child''s Meal', true, 100, true)
on conflict (name) do update
set is_child_meal = excluded.is_child_meal,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active,
    updated_at = timezone('utc', now());

create table if not exists public.rsvp_submissions (
    id bigint generated by default as identity primary key,
    group_id text,
    submitter_name text not null,
    submitter_email text,
    attending boolean not null,
    guest_count integer not null default 1,
    meal_choice text,
    dietary_notes text,
    special_message text,
    song_request text,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.address_submissions (
    id bigint generated by default as identity primary key,
    full_name text not null,
    email text,
    street text,
    street2 text,
    city text,
    state text,
    zip text,
    submitted_at timestamptz not null default timezone('utc', now()),
    raw_payload jsonb not null default '{}'::jsonb
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists access_passwords_set_updated_at on public.access_passwords;
create trigger access_passwords_set_updated_at
before update on public.access_passwords
for each row execute function public.set_updated_at();

drop trigger if exists guests_set_updated_at on public.guests;
create trigger guests_set_updated_at
before update on public.guests
for each row execute function public.set_updated_at();

drop trigger if exists menu_items_set_updated_at on public.menu_items;
create trigger menu_items_set_updated_at
before update on public.menu_items
for each row execute function public.set_updated_at();

create or replace function public.access_rank(level text)
returns integer
language sql
immutable
as $$
    select case lower(coalesce(level, ''))
        when 'family' then 1
        when 'party' then 2
        when 'admin' then 3
        else 0
    end;
$$;

create or replace function public.require_session(session_token text, required_level text default 'family')
returns text
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    session_level text;
begin
    delete from public.access_sessions where expires_at <= timezone('utc', now());

    select access_level
    into session_level
    from public.access_sessions
    where token_hash = encode(digest(coalesce(session_token, ''), 'sha256'), 'hex')
      and expires_at > timezone('utc', now())
    limit 1;

    if session_level is null then
        raise exception 'Unauthorized';
    end if;

    if public.access_rank(session_level) < public.access_rank(required_level) then
        raise exception 'Forbidden';
    end if;

    return session_level;
end;
$$;

create or replace function public.login_access(candidate_password text, session_ttl_ms bigint default 3600000)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    matched_level text;
    raw_token text;
begin
    select level
    into matched_level
    from public.access_passwords
    where (
        (level in ('family', 'party') and crypt(lower(coalesce(candidate_password, '')), password_hash) = password_hash)
        or (level = 'admin' and crypt(coalesce(candidate_password, ''), password_hash) = password_hash)
    )
    order by public.access_rank(level) desc
    limit 1;

    if matched_level is null then
        raise exception 'Invalid password.';
    end if;

    raw_token := encode(gen_random_bytes(32), 'hex');

    insert into public.access_sessions (token_hash, access_level, expires_at)
    values (
        encode(digest(raw_token, 'sha256'), 'hex'),
        matched_level,
        timezone('utc', now()) + interval '1 millisecond' * greatest(session_ttl_ms, 60000)
    );

    return jsonb_build_object(
        'success', true,
        'token', raw_token,
        'accessLevel', matched_level,
        'expiresIn', greatest(session_ttl_ms, 60000)
    );
end;
$$;

create or replace function public.get_access_session(session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    session_level text;
    session_expiry timestamptz;
    expires_in_ms bigint;
begin
    select access_level, expires_at
    into session_level, session_expiry
    from public.access_sessions
    where token_hash = encode(digest(coalesce(session_token, ''), 'sha256'), 'hex')
      and expires_at > timezone('utc', now())
    limit 1;

    if session_level is null then
        raise exception 'Unauthorized';
    end if;

    expires_in_ms := greatest(
        0,
        floor((extract(epoch from session_expiry) - extract(epoch from timezone('utc', now()))) * 1000)
    );

    return jsonb_build_object(
        'success', true,
        'accessLevel', session_level,
        'expiresIn', expires_in_ms
    );
end;
$$;

create or replace function public.logout_access(session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
    delete from public.access_sessions
    where token_hash = encode(digest(coalesce(session_token, ''), 'sha256'), 'hex');

    return jsonb_build_object('success', true);
end;
$$;

-- Drop the old 2-parameter signature before recreating with the new 3-parameter one.
drop function if exists public.search_guest_groups(text, integer);
drop function if exists public.search_guest_groups(text, integer, boolean);

create or replace function public.search_guest_groups(
    search_name text,
    max_results integer default 5,
    require_rehearsal_eligible boolean default false,
    require_hmu_eligible boolean default false
)
returns jsonb
language sql
security definer
set search_path = public
as $$
with tokens as (
    select regexp_split_to_array(trim(coalesce(search_name, '')), '\s+') as parts
), filtered as (
    select g.*
    from public.guests g, tokens t
    where cardinality(t.parts) >= 2
      and lower(g.full_name) like '%' || lower(t.parts[1]) || '%'
      and lower(g.full_name) like '%' || lower(t.parts[cardinality(t.parts)]) || '%'
      and (not require_rehearsal_eligible or g.is_invited_to_rehearsal_lunch = true)
      and (not require_hmu_eligible or g.is_hmu_eligible = true)
), grouped as (
    select distinct group_id
    from filtered
    order by group_id
    limit greatest(coalesce(max_results, 5), 1)
)
select coalesce(jsonb_agg(
    jsonb_build_object(
        'groupId', grp.group_id,
        'primaryGuest', coalesce((
            select full_name
            from public.guests
            where group_id = grp.group_id
              and (not require_rehearsal_eligible or is_invited_to_rehearsal_lunch = true)
              and (not require_hmu_eligible or is_hmu_eligible = true)
            order by is_primary desc, full_name asc
            limit 1
        ), ''),
        'guests', coalesce((
            select jsonb_agg(jsonb_build_object(
                'id', guest.id,
                'fullName', guest.full_name,
                'email', guest.email,
                'isPrimary', guest.is_primary,
                'isPlusOne', guest.is_plus_one,
                'isChild', guest.is_child,
                'isHmuEligible', guest.is_hmu_eligible,
                'isInvitedToRehearsalLunch', guest.is_invited_to_rehearsal_lunch,
                'hmuSelection', guest.hmu_selection,
                'notes', guest.notes,
                'rsvpStatus', guest.rsvp_status,
                'mealChoice', guest.meal_choice,
                'dietaryNotes', guest.dietary_notes,
                'addressLine1', guest.address_line1,
                'addressLine2', guest.address_line2,
                'city', guest.city,
                'state', guest.state,
                'postalCode', guest.postal_code
            ) order by guest.is_primary desc, guest.full_name asc)
            from public.guests guest
            where guest.group_id = grp.group_id
              and (not require_rehearsal_eligible or guest.is_invited_to_rehearsal_lunch = true)
              and (not require_hmu_eligible or guest.is_hmu_eligible = true)
        ), '[]'::jsonb)
    )
), '[]'::jsonb)
from grouped grp;
$$;

create or replace function public.submit_rsvp(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    submitter_name text := trim(coalesce(payload->>'name', payload->>'rsvpName', ''));
    submitter_email text := trim(coalesce(payload->>'email', payload->>'rsvpEmail', ''));
    guest_group_id text := nullif(trim(coalesce(payload->>'guestGroupId', '')), '');
    normalized_dietary text := nullif(trim(coalesce(payload->>'dietaryRestrictions', '')), '');
    normalized_message text := nullif(trim(coalesce(payload->>'specialMessage', '')), '');
    normalized_song_request text := nullif(trim(coalesce(payload->>'songRequest', '')), '');
    normalized_meal_choice text := nullif(trim(coalesce(payload->>'mealChoice', '')), '');
    guest_responses jsonb := coalesce(payload->'guestResponses', '[]'::jsonb);
    child_meal_name text := coalesce((
        select mi.name
        from public.menu_items mi
        where mi.is_active = true
          and mi.is_child_meal = true
        order by mi.sort_order asc, mi.id asc
        limit 1
    ), 'Child''s Meal');
    accepted_count integer := 0;
    attending_flag boolean := false;
begin
    if submitter_name = '' then
        raise exception 'RSVP name is required.';
    end if;

    if submitter_email = '' then
        raise exception 'RSVP email is required.';
    end if;

    if guest_group_id is null and jsonb_array_length(guest_responses) > 0 then
        raise exception 'guestGroupId is required when submitting per-guest responses.';
    end if;

    if exists (
        select 1
        from jsonb_array_elements(guest_responses) as entry(value)
        join public.guests guest
          on guest.id = nullif(entry.value->>'guestId', '')::bigint
         and guest.group_id = guest_group_id
        where lower(coalesce(entry.value->>'status', '')) = 'accepted'
          and (
              guest.is_plus_one = true
              or lower(coalesce(guest.full_name, '')) ~ '\m(guest|plus\s*one)\M'
          )
          and nullif(trim(coalesce(entry.value->>'name', '')), '') is null
    ) then
        raise exception 'Please enter the name for your plus one.';
    end if;

    select count(*) filter (where lower(coalesce(entry.value->>'status', '')) = 'accepted')
    into accepted_count
    from jsonb_array_elements(guest_responses) as entry(value);

    attending_flag := accepted_count > 0 or lower(coalesce(payload->>'attending', '')) in ('yes', 'true');

    insert into public.rsvp_submissions (
        group_id,
        submitter_name,
        submitter_email,
        attending,
        guest_count,
        meal_choice,
        dietary_notes,
        special_message,
        song_request
    ) values (
        guest_group_id,
        submitter_name,
        submitter_email,
        attending_flag,
        greatest(coalesce(nullif(payload->>'guestCount', '')::integer, accepted_count, 1), 1),
        normalized_meal_choice,
        normalized_dietary,
        normalized_message,
        normalized_song_request
    );

    if jsonb_array_length(guest_responses) > 0 then
        update public.guests guest
        set rsvp_status = case lower(coalesce(entry.value->>'status', ''))
                when 'accepted' then 'accepted'
                when 'declined' then 'declined'
                else guest.rsvp_status
            end,
            meal_choice = case
                when lower(coalesce(entry.value->>'status', '')) = 'accepted' and guest.is_child then child_meal_name
                when lower(coalesce(entry.value->>'status', '')) = 'accepted' then coalesce(nullif(trim(coalesce(entry.value->>'mealChoice', '')), ''), guest.meal_choice)
                else guest.meal_choice
            end,
            full_name = coalesce(nullif(trim(coalesce(entry.value->>'name', '')), ''), guest.full_name),
            last_rsvp_at = timezone('utc', now()),
            updated_at = timezone('utc', now())
        from jsonb_array_elements(guest_responses) as entry(value)
        where guest.id = nullif(entry.value->>'guestId', '')::bigint
          and guest.group_id = guest_group_id;
    elsif guest_group_id is not null then
        update public.guests
        set rsvp_status = case when attending_flag then 'accepted' else 'declined' end,
            meal_choice = case
                when attending_flag and is_child then child_meal_name
                else coalesce(normalized_meal_choice, meal_choice)
            end,
            last_rsvp_at = timezone('utc', now()),
            updated_at = timezone('utc', now())
        where group_id = guest_group_id;
    end if;

    if guest_group_id is not null and normalized_dietary is not null then
        update public.guests
        set dietary_notes = normalized_dietary,
            updated_at = timezone('utc', now())
        where group_id = guest_group_id;
    end if;

    return jsonb_build_object(
        'success', true,
        'status', case when attending_flag then 'accepted' else 'declined' end,
        'message', case when attending_flag
            then 'Thank you for your RSVP! We cannot wait to celebrate with you.'
            else 'We appreciate the update and will miss you at the celebration.'
        end
    );
end;
$$;

create or replace function public.save_address_submission(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.address_submissions (
        full_name,
        email,
        street,
        street2,
        city,
        state,
        zip,
        raw_payload
    ) values (
        trim(coalesce(payload->>'fullName', '')),
        nullif(trim(coalesce(payload->>'email', '')), ''),
        nullif(trim(coalesce(payload->>'street', '')), ''),
        nullif(trim(coalesce(payload->>'street2', '')), ''),
        nullif(trim(coalesce(payload->>'city', '')), ''),
        nullif(trim(coalesce(payload->>'state', '')), ''),
        nullif(trim(coalesce(payload->>'zip', '')), ''),
        coalesce(payload, '{}'::jsonb)
    );

    return jsonb_build_object('success', true, 'message', 'Thank you! Your address has been saved.');
end;
$$;

create or replace function public.list_admin_guests(session_token text)
returns jsonb
language sql
security definer
set search_path = public
as $$
    with authorized as (
        select public.require_session(session_token, 'admin')
    )
    select coalesce(jsonb_agg(jsonb_build_object(
        'id', guest.id,
        'fullName', guest.full_name,
        'email', guest.email,
        'groupId', guest.group_id,
        'isPrimary', guest.is_primary,
        'isPlusOne', guest.is_plus_one,
        'isChild', guest.is_child,
        'isHmuEligible', guest.is_hmu_eligible,
        'hmuSelection', guest.hmu_selection,
        'notes', guest.notes,
        'rsvpStatus', guest.rsvp_status,
        'mealChoice', guest.meal_choice,
        'dietaryNotes', guest.dietary_notes,
        'addressLine1', guest.address_line1,
        'addressLine2', guest.address_line2,
        'city', guest.city,
        'state', guest.state,
        'postalCode', guest.postal_code,
        'rsvpSubmitterName', latest_rsvp.submitter_name,
        'rsvpSubmitterEmail', latest_rsvp.submitter_email,
        'rsvpSpecialMessage', latest_rsvp.special_message,
        'rsvpSongRequest', latest_rsvp.song_request,
        'rsvpSubmittedAt', latest_rsvp.created_at,
        'lastRsvpAt', guest.last_rsvp_at,
        'isInvitedToRehearsalLunch', guest.is_invited_to_rehearsal_lunch
    ) order by guest.group_id, guest.is_primary desc, guest.full_name asc), '[]'::jsonb)
    from public.guests guest
    cross join authorized
    left join lateral (
        select
            r.submitter_name,
            r.submitter_email,
            r.special_message,
            r.song_request,
            r.created_at
        from public.rsvp_submissions r
        where r.group_id = guest.group_id
        order by r.created_at desc, r.id desc
        limit 1
    ) latest_rsvp on true;
$$;

create or replace function public.admin_upsert_guest(session_token text, guest_id bigint, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    saved_id bigint;
begin
    perform public.require_session(session_token, 'admin');

    if trim(coalesce(payload->>'fullName', '')) = '' or trim(coalesce(payload->>'groupId', '')) = '' then
        raise exception 'fullName and groupId are required.';
    end if;

    if guest_id is null then
        insert into public.guests (
            full_name,
            email,
            group_id,
            is_primary,
            is_plus_one,
            is_child,
            is_hmu_eligible,
            notes,
            rsvp_status,
            hmu_selection,
            meal_choice,
            dietary_notes,
            address_line1,
            address_line2,
            city,
            state,
            postal_code,
            is_invited_to_rehearsal_lunch
        ) values (
            trim(payload->>'fullName'),
            nullif(trim(coalesce(payload->>'email', '')), ''),
            trim(payload->>'groupId'),
            coalesce((payload->>'isPrimary')::boolean, false),
            coalesce((payload->>'isPlusOne')::boolean, false),
            coalesce((payload->>'isChild')::boolean, false),
            coalesce((payload->>'isHmuEligible')::boolean, false),
            nullif(trim(coalesce(payload->>'notes', '')), ''),
            coalesce(nullif(trim(coalesce(payload->>'rsvpStatus', '')), ''), 'pending'),
            coalesce(nullif(trim(coalesce(payload->>'hmuSelection', '')), ''), 'not_selected'),
            nullif(trim(coalesce(payload->>'mealChoice', '')), ''),
            nullif(trim(coalesce(payload->>'dietaryNotes', '')), ''),
            nullif(trim(coalesce(payload->>'addressLine1', '')), ''),
            nullif(trim(coalesce(payload->>'addressLine2', '')), ''),
            nullif(trim(coalesce(payload->>'city', '')), ''),
            nullif(trim(coalesce(payload->>'state', '')), ''),
            nullif(trim(coalesce(payload->>'postalCode', '')), ''),
            coalesce((payload->>'isInvitedToRehearsalLunch')::boolean, false)
        ) returning id into saved_id;
    else
        update public.guests
        set full_name = trim(payload->>'fullName'),
            email = nullif(trim(coalesce(payload->>'email', '')), ''),
            group_id = trim(payload->>'groupId'),
            is_primary = coalesce((payload->>'isPrimary')::boolean, false),
            is_plus_one = coalesce((payload->>'isPlusOne')::boolean, false),
            is_child = coalesce((payload->>'isChild')::boolean, false),
            is_hmu_eligible = coalesce((payload->>'isHmuEligible')::boolean, false),
            notes = nullif(trim(coalesce(payload->>'notes', '')), ''),
            rsvp_status = coalesce(nullif(trim(coalesce(payload->>'rsvpStatus', '')), ''), 'pending'),
            hmu_selection = coalesce(nullif(trim(coalesce(payload->>'hmuSelection', '')), ''), 'not_selected'),
            meal_choice = nullif(trim(coalesce(payload->>'mealChoice', '')), ''),
            dietary_notes = nullif(trim(coalesce(payload->>'dietaryNotes', '')), ''),
            address_line1 = nullif(trim(coalesce(payload->>'addressLine1', '')), ''),
            address_line2 = nullif(trim(coalesce(payload->>'addressLine2', '')), ''),
            city = nullif(trim(coalesce(payload->>'city', '')), ''),
            state = nullif(trim(coalesce(payload->>'state', '')), ''),
            postal_code = nullif(trim(coalesce(payload->>'postalCode', '')), ''),
            is_invited_to_rehearsal_lunch = coalesce((payload->>'isInvitedToRehearsalLunch')::boolean, false),
            updated_at = timezone('utc', now())
        where id = guest_id
        returning id into saved_id;

        if saved_id is null then
            raise exception 'Guest not found.';
        end if;
    end if;

    return jsonb_build_object('success', true, 'id', saved_id);
end;
$$;

create or replace function public.admin_delete_guest(session_token text, guest_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
    perform public.require_session(session_token, 'admin');
    delete from public.guests where id = guest_id;
    return jsonb_build_object('success', true);
end;
$$;

create or replace function public.admin_import_guests(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    entry jsonb;
    inserted_count integer := 0;
begin
    perform public.require_session(session_token, 'admin');

    for entry in select value from jsonb_array_elements(coalesce(payload, '[]'::jsonb))
    loop
        if trim(coalesce(entry->>'fullName', '')) = '' or trim(coalesce(entry->>'groupId', '')) = '' then
            continue;
        end if;

        insert into public.guests (
            full_name,
            email,
            group_id,
            is_primary,
            is_plus_one,
            is_child,
            is_hmu_eligible,
            notes,
            rsvp_status,
            hmu_selection,
            meal_choice,
            dietary_notes,
            address_line1,
            address_line2,
            city,
            state,
            postal_code
        ) values (
            trim(entry->>'fullName'),
            nullif(trim(coalesce(entry->>'email', '')), ''),
            trim(entry->>'groupId'),
            coalesce((entry->>'isPrimary')::boolean, false),
            coalesce((entry->>'isPlusOne')::boolean, false),
            coalesce((entry->>'isChild')::boolean, false),
            coalesce((entry->>'isHmuEligible')::boolean, false),
            nullif(trim(coalesce(entry->>'notes', '')), ''),
            coalesce(nullif(trim(coalesce(entry->>'rsvpStatus', '')), ''), 'pending'),
            coalesce(nullif(trim(coalesce(entry->>'hmuSelection', '')), ''), 'not_selected'),
            nullif(trim(coalesce(entry->>'mealChoice', '')), ''),
            nullif(trim(coalesce(entry->>'dietaryNotes', '')), ''),
            nullif(trim(coalesce(entry->>'addressLine1', '')), ''),
            nullif(trim(coalesce(entry->>'addressLine2', '')), ''),
            nullif(trim(coalesce(entry->>'city', '')), ''),
            nullif(trim(coalesce(entry->>'state', '')), ''),
            nullif(trim(coalesce(entry->>'postalCode', '')), '')
        );

        inserted_count := inserted_count + 1;
    end loop;

    return jsonb_build_object('success', true, 'inserted', inserted_count);
end;
$$;

create table if not exists public.registry_items (
    id text primary key,
    name text not null,
    description text,
    price numeric,
    quantity_requested integer,
    quantity_purchased integer,
    image_url text,
    store_name text,
    product_url text,
    category text,
    is_purchased boolean not null default false,
    fetched_at timestamptz not null default timezone('utc', now())
);

create or replace function public.get_menu_options()
returns jsonb
language sql
security definer
set search_path = public
as $$
    select jsonb_build_object(
        'adultMeals', coalesce((
            select jsonb_agg(mi.name order by mi.sort_order asc, mi.id asc)
            from public.menu_items mi
            where mi.is_active = true
              and mi.is_child_meal = false
        ), '[]'::jsonb),
        'childMeal', (
            select mi.name
            from public.menu_items mi
            where mi.is_active = true
              and mi.is_child_meal = true
            order by mi.sort_order asc, mi.id asc
            limit 1
        )
    );
$$;

alter table public.registry_items
    add column if not exists item_type text,
    add column if not exists action_label text,
    add column if not exists source_product_url text,
    add column if not exists source_store_name text,
    add column if not exists page_url text,
    add column if not exists registry_id text,
    add column if not exists registry_image_url text,
    add column if not exists resolved_image_url text,
    add column if not exists image_marked_for_retry boolean not null default false,
    add column if not exists image_manually_cleared boolean not null default false,
    add column if not exists image_blacklisted boolean not null default false,
    add column if not exists image_suspicious boolean not null default false,
    add column if not exists image_low_confidence boolean not null default false;

drop function if exists public.get_registry_items();

create function public.get_registry_items()
returns table (
    id text,
    name text,
    description text,
    price numeric,
    quantity_requested integer,
    quantity_purchased integer,
    image_url text,
    registry_image_url text,
    resolved_image_url text,
    store_name text,
    product_url text,
    source_product_url text,
    source_store_name text,
    category text,
    is_purchased boolean,
    fetched_at timestamptz,
    item_type text,
    action_label text,
    page_url text,
    registry_id text
)
language sql
security definer
set search_path = public
as $$
    select
        id, name, description, price,
        quantity_requested, quantity_purchased,
        image_url, registry_image_url, resolved_image_url, store_name, product_url, source_product_url, source_store_name, category,
        is_purchased, fetched_at,
        item_type, action_label, page_url, registry_id
    from public.registry_items
    order by is_purchased asc, name asc;
$$;

alter table public.access_passwords enable row level security;
alter table public.access_sessions enable row level security;
alter table public.guests enable row level security;
alter table public.rsvp_submissions enable row level security;
alter table public.address_submissions enable row level security;
alter table public.registry_items enable row level security;

drop policy if exists "Public read registry items" on public.registry_items;

create policy "Public read registry items"
    on public.registry_items for select
    to anon, authenticated
    using (true);

revoke all on public.access_passwords from anon, authenticated;
revoke all on public.access_sessions from anon, authenticated;
revoke all on public.guests from anon, authenticated;
revoke all on public.rsvp_submissions from anon, authenticated;
revoke all on public.address_submissions from anon, authenticated;

grant execute on function public.login_access(text, bigint) to anon, authenticated;
grant execute on function public.get_access_session(text) to anon, authenticated;
grant execute on function public.logout_access(text) to anon, authenticated;
grant execute on function public.search_guest_groups(text, integer, boolean) to anon, authenticated;
grant execute on function public.submit_rsvp(jsonb) to anon, authenticated;
grant execute on function public.save_address_submission(jsonb) to anon, authenticated;
grant execute on function public.get_menu_options() to anon, authenticated;
grant execute on function public.list_admin_guests(text) to anon, authenticated;
grant execute on function public.admin_upsert_guest(text, bigint, jsonb) to anon, authenticated;
grant execute on function public.admin_delete_guest(text, bigint) to anon, authenticated;
grant execute on function public.admin_import_guests(text, jsonb) to anon, authenticated;
grant execute on function public.get_registry_items() to anon, authenticated;

-- HMU (Hair & Makeup) preferences are stored on guests
drop function if exists public.list_admin_hmu_submissions(text);
drop table if exists public.hmu_submissions;

create or replace function public.save_hmu_submission(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    normalized_guest_id text := nullif(trim(coalesce(payload->>'guestId', '')), '');
    normalized_name text := trim(coalesce(payload->>'fullName', ''));
    wants_hair boolean := coalesce((payload->>'wantsHair')::boolean, false);
    wants_makeup boolean := coalesce((payload->>'wantsMakeup')::boolean, false);
    wants_opt_out boolean := coalesce((payload->>'wantsOptOut')::boolean, false);
    normalized_selection text := case
        when wants_opt_out then 'opt_out'
        when wants_hair and wants_makeup then 'hair_makeup'
        when wants_hair then 'hair'
        when wants_makeup then 'makeup'
        else 'not_selected'
    end;
    matching_guest_id bigint;
    is_eligible boolean := false;
    matching_count integer := 0;
begin
    if normalized_selection = 'not_selected' then
        raise exception 'Please choose Hair, Makeup, or Opt-out.';
    end if;

    if normalized_guest_id is not null and normalized_guest_id !~ '^\d+$' then
        raise exception 'Invalid guest selection.';
    end if;

    if normalized_guest_id is not null then
        select g.id, g.is_hmu_eligible
        into matching_guest_id, is_eligible
        from public.guests g
        where g.id = normalized_guest_id::bigint
        limit 1;
    else
        if normalized_name = '' then
            raise exception 'Name is required.';
        end if;

        select count(*)
        into matching_count
        from public.guests g
        where lower(trim(g.full_name)) = lower(normalized_name)
          and g.is_hmu_eligible = true;

        if matching_count > 1 then
            raise exception 'Multiple eligible guests match that name. Please use Find Me and select your name.';
        end if;

        select g.id, g.is_hmu_eligible
        into matching_guest_id, is_eligible
        from public.guests g
        where lower(trim(g.full_name)) = lower(normalized_name)
          and g.is_hmu_eligible = true
        order by g.id
        limit 1;
    end if;

    if matching_guest_id is null then
        raise exception 'We could not match that guest. Please use Find Me and select your name.';
    end if;

    if not is_eligible then
        raise exception 'This guest is not marked as eligible for hair and makeup.';
    end if;

    update public.guests
    set hmu_selection = normalized_selection,
        updated_at = timezone('utc', now())
    where id = matching_guest_id;

    return jsonb_build_object('success', true, 'message', 'Thanks! We will reach out to confirm.');
end;
$$;

grant execute on function public.save_hmu_submission(jsonb) to anon, authenticated;

-- Rehearsal lunch: invited flag on guests
alter table public.guests
    add column if not exists is_invited_to_rehearsal_lunch boolean not null default false;

-- Rehearsal lunch RSVPs table
create table if not exists public.rehearsal_lunch_rsvps (
    id bigint generated by default as identity primary key,
    full_name text not null,
    email text,
    rsvp_status text not null default 'accepted' check (rsvp_status in ('accepted', 'declined')),
    submitted_at timestamptz not null default timezone('utc', now())
);

revoke all on public.rehearsal_lunch_rsvps from anon, authenticated;

create or replace function public.submit_rehearsal_lunch_rsvp(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
    if trim(coalesce(payload->>'fullName', '')) = '' then
        raise exception 'Name is required.';
    end if;

    insert into public.rehearsal_lunch_rsvps (full_name, email, rsvp_status)
    values (
        trim(payload->>'fullName'),
        nullif(trim(coalesce(payload->>'email', '')), ''),
        coalesce(nullif(trim(coalesce(payload->>'rsvpStatus', '')), ''), 'accepted')
    );

    return jsonb_build_object('success', true, 'message', 'Got it! Thanks for your RSVP.');
end;
$$;

create or replace function public.list_admin_rehearsal_lunch_rsvps(session_token text)
returns jsonb
language sql
security definer
set search_path = public
as $$
    with authorized as (
        select public.require_session(session_token, 'admin')
    )
    select coalesce(jsonb_agg(jsonb_build_object(
        'id', r.id,
        'fullName', r.full_name,
        'email', r.email,
        'rsvpStatus', r.rsvp_status,
        'submittedAt', r.submitted_at
    ) order by r.submitted_at desc), '[]'::jsonb)
    from public.rehearsal_lunch_rsvps r, authorized;
$$;

grant execute on function public.submit_rehearsal_lunch_rsvp(jsonb) to anon, authenticated;
grant execute on function public.list_admin_rehearsal_lunch_rsvps(text) to anon, authenticated;

update public.guests
set is_invited_to_rehearsal_lunch = true,
    is_hmu_eligible = true,
    updated_at = timezone('utc', now())
where lower(trim(full_name)) = 'alyssa graham';

-- Seating chart (forked from gabriel1ll7/Seating-Planner, "Seating.Art").
-- We don't own or run their app; this table only backs our own hard fork
-- of the frontend, served statically from /seating-chart and talking to
-- the seating-chart-api edge function instead of their Express server.
-- Multiple venues, each with a shareable slug, an edit PIN (always on),
-- and an optional, toggleable view PIN. All access goes through that
-- edge function (service role) — never directly from anon/authenticated
-- clients, so PIN checks stay rate-limited.
create table if not exists public.seating_chart_venues (
    slug text primary key,
    venue_data jsonb not null default '{}'::jsonb,
    hashed_edit_pin text,
    hashed_view_pin text,
    view_pin_required boolean not null default false,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists seating_chart_venues_set_updated_at on public.seating_chart_venues;
create trigger seating_chart_venues_set_updated_at
before update on public.seating_chart_venues
for each row execute function public.set_updated_at();

alter table public.seating_chart_venues enable row level security;
revoke all on public.seating_chart_venues from anon, authenticated;

-- Tracks PIN validation attempts per (slug, which PIN, hashed client IP)
-- so a 4-digit PIN (10,000 possibilities) can't be brute-forced, and
-- exhausting attempts against one PIN doesn't lock out the other.
create table if not exists public.seating_chart_pin_attempts (
    id bigint generated by default as identity primary key,
    slug text not null,
    pin_kind text not null default 'edit' check (pin_kind in ('view', 'edit')),
    ip_hash text not null,
    attempted_at timestamptz not null default timezone('utc', now())
);

create index if not exists seating_chart_pin_attempts_lookup_idx
    on public.seating_chart_pin_attempts (slug, pin_kind, ip_hash, attempted_at);

alter table public.seating_chart_pin_attempts enable row level security;
revoke all on public.seating_chart_pin_attempts from anon, authenticated;

-- Records an attempt and raises if this (slug, kind, ip) pair has hit
-- the rate limit. Called by seating_chart_check_pin before every
-- comparison.
create or replace function public.seating_chart_record_pin_attempt(
    target_slug text,
    requested_pin_kind text,
    client_ip text
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    hashed_ip text := encode(digest(coalesce(client_ip, 'unknown'), 'sha256'), 'hex');
    recent_attempts integer;
begin
    delete from public.seating_chart_pin_attempts
    where attempted_at <= timezone('utc', now()) - interval '15 minutes';

    select count(*)
    into recent_attempts
    from public.seating_chart_pin_attempts
    where slug = target_slug
      and pin_kind = requested_pin_kind
      and ip_hash = hashed_ip
      and attempted_at > timezone('utc', now()) - interval '15 minutes';

    if recent_attempts >= 10 then
        raise exception 'Too many PIN attempts for this chart. Try again in a few minutes.';
    end if;

    insert into public.seating_chart_pin_attempts (slug, pin_kind, ip_hash)
    values (target_slug, requested_pin_kind, hashed_ip);
end;
$$;

-- Shared by validate-pin and save-with-pin so brute-forcing via either
-- path counts against the same rate limit. pin_kind selects which of
-- the venue's two PINs to check against.
create or replace function public.seating_chart_check_pin(
    target_slug text,
    pin_kind text,
    candidate_pin text,
    client_ip text default null
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    stored_hash text;
begin
    if pin_kind not in ('view', 'edit') then
        raise exception 'Invalid pin_kind.';
    end if;

    perform public.seating_chart_record_pin_attempt(target_slug, pin_kind, client_ip);

    select case pin_kind when 'view' then hashed_view_pin else hashed_edit_pin end
    into stored_hash
    from public.seating_chart_venues
    where slug = target_slug;

    if stored_hash is null or candidate_pin is null or candidate_pin = '' then
        return false;
    end if;

    return crypt(candidate_pin, stored_hash) = stored_hash;
end;
$$;

-- Admin-only: create a new venue with a caller-supplied slug (the worker
-- generates a human-friendly one, e.g. "warm-table-482", with retry on
-- collision) and an auto-generated 4-digit edit PIN, returned once in
-- plaintext so the admin can share it. No view PIN by default — viewing
-- starts open, same as before this venue existed.
create or replace function public.seating_chart_create_venue(
    session_token text,
    slug text,
    event_title text default 'New Event'
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    generated_pin text;
begin
    perform public.require_session(session_token, 'admin');

    if trim(coalesce(slug, '')) = '' then
        raise exception 'slug is required.';
    end if;

    generated_pin := lpad(floor(random() * 10000)::int::text, 4, '0');

    insert into public.seating_chart_venues (slug, venue_data, hashed_edit_pin)
    values (
        slug,
        jsonb_build_object(
            'shapes', '[]'::jsonb,
            'guests', '[]'::jsonb,
            'eventTitle', coalesce(nullif(trim(event_title), ''), 'New Event'),
            'tableCounter', 1
        ),
        crypt(generated_pin, gen_salt('bf'))
    );

    return jsonb_build_object('success', true, 'slug', slug, 'pin', generated_pin);
end;
$$;

-- Admin-only: list every venue (for the admin's venue picker).
create or replace function public.seating_chart_list_venues(session_token text)
returns jsonb
language sql
security definer
set search_path = public, extensions
as $$
    with authorized as (select public.require_session(session_token, 'admin'))
    select coalesce(jsonb_agg(jsonb_build_object(
        'slug', v.slug,
        'eventTitle', coalesce(v.venue_data->>'eventTitle', 'Untitled Event'),
        'updatedAt', v.updated_at,
        'hasEditPin', v.hashed_edit_pin is not null,
        'hasViewPin', v.hashed_view_pin is not null,
        'viewPinRequired', v.view_pin_required
    ) order by v.updated_at desc), '[]'::jsonb)
    from public.seating_chart_venues v, authorized;
$$;

-- Public (no session required): fetch a venue by slug. This is what
-- makes a chart "shareable". Editing always implies viewing, so a valid
-- edit_pin (or admin) satisfies a view-PIN requirement too. Returns a
-- locked payload (no venue_data) when a view PIN is required and
-- neither admin, edit_pin, nor view_pin checks out. Returns null if the
-- slug doesn't exist at all.
create or replace function public.seating_chart_get_venue(
    target_slug text,
    session_token text default null,
    view_pin text default null,
    edit_pin text default null,
    client_ip text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    row_data record;
    is_admin boolean := false;
    unlocked boolean := false;
begin
    select v.venue_data, v.updated_at, v.hashed_edit_pin, v.hashed_view_pin, v.view_pin_required
    into row_data
    from public.seating_chart_venues v
    where v.slug = target_slug;

    if not found then
        return null;
    end if;

    if session_token is not null and session_token <> '' then
        begin
            perform public.require_session(session_token, 'admin');
            is_admin := true;
        exception when others then
            is_admin := false;
        end;
    end if;

    if is_admin or not row_data.view_pin_required then
        unlocked := true;
    elsif edit_pin is not null and edit_pin <> ''
        and public.seating_chart_check_pin(target_slug, 'edit', edit_pin, client_ip) then
        unlocked := true;
    elsif view_pin is not null and view_pin <> ''
        and public.seating_chart_check_pin(target_slug, 'view', view_pin, client_ip) then
        unlocked := true;
    end if;

    if not unlocked then
        return jsonb_build_object(
            'slug', target_slug,
            'locked', true,
            'viewPinRequired', true,
            'hasEditPin', row_data.hashed_edit_pin is not null,
            'hasViewPin', row_data.hashed_view_pin is not null
        );
    end if;

    return jsonb_build_object(
        'slug', target_slug,
        'locked', false,
        'venueData', row_data.venue_data,
        'updatedAt', row_data.updated_at,
        'hasEditPin', row_data.hashed_edit_pin is not null,
        'hasViewPin', row_data.hashed_view_pin is not null,
        'viewPinRequired', row_data.view_pin_required
    );
end;
$$;

-- Save a venue's state. Allowed if session_token proves admin, OR
-- candidate_edit_pin matches that venue's edit PIN (rate-limited).
create or replace function public.seating_chart_save_venue(
    session_token text,
    target_slug text,
    new_venue_data jsonb,
    candidate_edit_pin text default null,
    client_ip text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    is_admin boolean := false;
    updated timestamptz;
begin
    if session_token is not null and session_token <> '' then
        begin
            perform public.require_session(session_token, 'admin');
            is_admin := true;
        exception when others then
            is_admin := false;
        end;
    end if;

    if not is_admin then
        if candidate_edit_pin is null or candidate_edit_pin = '' then
            raise exception 'Unauthorized';
        end if;
        if not public.seating_chart_check_pin(target_slug, 'edit', candidate_edit_pin, client_ip) then
            raise exception 'Incorrect PIN.';
        end if;
    end if;

    update public.seating_chart_venues
    set venue_data = new_venue_data
    where slug = target_slug
    returning updated_at into updated;

    if updated is null then
        raise exception 'Chart not found.';
    end if;

    return jsonb_build_object('success', true, 'updatedAt', updated);
end;
$$;

-- Admin-only: set or regenerate a venue's edit PIN. Returns the new PIN
-- once, in plaintext, so the admin can re-share it.
create or replace function public.seating_chart_set_edit_pin(
    session_token text,
    target_slug text,
    new_pin text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    resolved_pin text;
    updated timestamptz;
begin
    perform public.require_session(session_token, 'admin');

    resolved_pin := nullif(trim(coalesce(new_pin, '')), '');
    if resolved_pin is null then
        resolved_pin := lpad(floor(random() * 10000)::int::text, 4, '0');
    elsif resolved_pin !~ '^\d{4}$' then
        raise exception 'PIN must be a 4-digit number.';
    end if;

    update public.seating_chart_venues
    set hashed_edit_pin = crypt(resolved_pin, gen_salt('bf'))
    where slug = target_slug
    returning updated_at into updated;

    if updated is null then
        raise exception 'Chart not found.';
    end if;

    return jsonb_build_object('success', true, 'pin', resolved_pin);
end;
$$;

-- Admin-only: toggle whether viewing this venue requires a PIN. Turning
-- it on (re)generates or accepts a custom view PIN; turning it off
-- clears the stored view PIN entirely, so re-enabling later always
-- starts from a fresh one.
create or replace function public.seating_chart_set_view_pin(
    session_token text,
    target_slug text,
    enabled boolean,
    new_pin text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    resolved_pin text;
    updated timestamptz;
begin
    perform public.require_session(session_token, 'admin');

    if not enabled then
        update public.seating_chart_venues
        set view_pin_required = false,
            hashed_view_pin = null
        where slug = target_slug
        returning updated_at into updated;

        if updated is null then
            raise exception 'Chart not found.';
        end if;

        return jsonb_build_object('success', true, 'enabled', false, 'pin', null);
    end if;

    resolved_pin := nullif(trim(coalesce(new_pin, '')), '');
    if resolved_pin is null then
        resolved_pin := lpad(floor(random() * 10000)::int::text, 4, '0');
    elsif resolved_pin !~ '^\d{4}$' then
        raise exception 'PIN must be a 4-digit number.';
    end if;

    update public.seating_chart_venues
    set view_pin_required = true,
        hashed_view_pin = crypt(resolved_pin, gen_salt('bf'))
    where slug = target_slug
    returning updated_at into updated;

    if updated is null then
        raise exception 'Chart not found.';
    end if;

    return jsonb_build_object('success', true, 'enabled', true, 'pin', resolved_pin);
end;
$$;

-- Public (no session required), but rate-limited via seating_chart_check_pin:
-- lets a link recipient unlock view or edit access by entering the
-- relevant PIN.
create or replace function public.seating_chart_validate_pin(
    target_slug text,
    pin_kind text,
    candidate_pin text,
    client_ip text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
    return jsonb_build_object(
        'success',
        public.seating_chart_check_pin(target_slug, pin_kind, candidate_pin, client_ip)
    );
end;
$$;
