-- Restore menu option support for projects created before menu_items existed,
-- and enforce required plus-one/placeholder names inside RSVP submissions.
create table if not exists public.menu_items (
    id bigint generated by default as identity primary key,
    name text not null unique,
    is_child_meal boolean not null default false,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

insert into public.menu_items (name, is_child_meal, sort_order, is_active)
values
    ('Gnocchi', false, 10, true),
    ('Atlantic Salmon', false, 20, true),
    ('Flank Steak', false, 30, true),
    ('Child''s Meal', true, 100, true)
on conflict (name) do update
set is_child_meal = excluded.is_child_meal,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active,
    updated_at = timezone('utc', now());

drop trigger if exists menu_items_set_updated_at on public.menu_items;
create trigger menu_items_set_updated_at
before update on public.menu_items
for each row execute function public.set_updated_at();

create or replace function public.get_menu_options()
returns jsonb
language sql
security definer
set search_path = public
as $$
    select jsonb_build_object(
        'adultMeals', coalesce((
            select jsonb_agg(mi.name order by mi.sort_order asc, mi.id asc)
            from public.menu_items mi
            where mi.is_active = true
              and mi.is_child_meal = false
        ), '[]'::jsonb),
        'childMeal', coalesce((
            select mi.name
            from public.menu_items mi
            where mi.is_active = true
              and mi.is_child_meal = true
            order by mi.sort_order asc, mi.id asc
            limit 1
        ), 'Child''s Meal')
    );
$$;

create or replace function public.submit_rsvp(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    submitter_name text := trim(coalesce(payload->>'name', payload->>'rsvpName', ''));
    submitter_email text := trim(coalesce(payload->>'email', payload->>'rsvpEmail', ''));
    guest_group_id text := nullif(trim(coalesce(payload->>'guestGroupId', '')), '');
    normalized_dietary text := nullif(trim(coalesce(payload->>'dietaryRestrictions', '')), '');
    normalized_message text := nullif(trim(coalesce(payload->>'specialMessage', '')), '');
    normalized_song_request text := nullif(trim(coalesce(payload->>'songRequest', '')), '');
    normalized_meal_choice text := nullif(trim(coalesce(payload->>'mealChoice', '')), '');
    guest_responses jsonb := coalesce(payload->'guestResponses', '[]'::jsonb);
    child_meal_name text := coalesce((
        select mi.name
        from public.menu_items mi
        where mi.is_active = true
          and mi.is_child_meal = true
        order by mi.sort_order asc, mi.id asc
        limit 1
    ), 'Child''s Meal');
    accepted_count integer := 0;
    attending_flag boolean := false;
begin
    if submitter_name = '' then
        raise exception 'RSVP name is required.';
    end if;

    if submitter_email = '' then
        raise exception 'RSVP email is required.';
    end if;

    if guest_group_id is null and jsonb_array_length(guest_responses) > 0 then
        raise exception 'guestGroupId is required when submitting per-guest responses.';
    end if;

    if exists (
        select 1
        from jsonb_array_elements(guest_responses) as entry(value)
        join public.guests guest
          on guest.id = nullif(entry.value->>'guestId', '')::bigint
         and guest.group_id = guest_group_id
        where lower(coalesce(entry.value->>'status', '')) = 'accepted'
          and (
              guest.is_plus_one = true
              or lower(coalesce(guest.full_name, '')) ~ '\m(guest|plus\s*one)\M'
          )
          and nullif(trim(coalesce(entry.value->>'name', '')), '') is null
    ) then
        raise exception 'Please enter the name for your plus one.';
    end if;

    select count(*) filter (where lower(coalesce(entry.value->>'status', '')) = 'accepted')
    into accepted_count
    from jsonb_array_elements(guest_responses) as entry(value);

    attending_flag := accepted_count > 0 or lower(coalesce(payload->>'attending', '')) in ('yes', 'true');

    insert into public.rsvp_submissions (
        group_id,
        submitter_name,
        submitter_email,
        attending,
        guest_count,
        meal_choice,
        dietary_notes,
        special_message,
        song_request
    ) values (
        guest_group_id,
        submitter_name,
        submitter_email,
        attending_flag,
        greatest(coalesce(nullif(payload->>'guestCount', '')::integer, accepted_count, 1), 1),
        normalized_meal_choice,
        normalized_dietary,
        normalized_message,
        normalized_song_request
    );

    if jsonb_array_length(guest_responses) > 0 then
        update public.guests guest
        set rsvp_status = case lower(coalesce(entry.value->>'status', ''))
                when 'accepted' then 'accepted'
                when 'declined' then 'declined'
                else guest.rsvp_status
            end,
            meal_choice = case
                when lower(coalesce(entry.value->>'status', '')) = 'accepted' and guest.is_child then child_meal_name
                when lower(coalesce(entry.value->>'status', '')) = 'accepted' then coalesce(nullif(trim(coalesce(entry.value->>'mealChoice', '')), ''), guest.meal_choice)
                else guest.meal_choice
            end,
            full_name = coalesce(nullif(trim(coalesce(entry.value->>'name', '')), ''), guest.full_name),
            last_rsvp_at = timezone('utc', now()),
            updated_at = timezone('utc', now())
        from jsonb_array_elements(guest_responses) as entry(value)
        where guest.id = nullif(entry.value->>'guestId', '')::bigint
          and guest.group_id = guest_group_id;
    elsif guest_group_id is not null then
        update public.guests
        set rsvp_status = case when attending_flag then 'accepted' else 'declined' end,
            meal_choice = case
                when attending_flag and is_child then child_meal_name
                else coalesce(normalized_meal_choice, meal_choice)
            end,
            last_rsvp_at = timezone('utc', now()),
            updated_at = timezone('utc', now())
        where group_id = guest_group_id;
    end if;

    if guest_group_id is not null and normalized_dietary is not null then
        update public.guests
        set dietary_notes = normalized_dietary,
            updated_at = timezone('utc', now())
        where group_id = guest_group_id;
    end if;

    return jsonb_build_object(
        'success', true,
        'status', case when attending_flag then 'accepted' else 'declined' end,
        'message', case when attending_flag
            then 'Thank you for your RSVP! We cannot wait to celebrate with you.'
            else 'We appreciate the update and will miss you at the celebration.'
        end
    );
end;
$$;

grant execute on function public.get_menu_options() to anon, authenticated;
grant execute on function public.submit_rsvp(jsonb) to anon, authenticated;
notify pgrst, 'reload schema';
