-- Seating chart: multi-venue + shareable slugs + per-venue PIN protection.
--
-- Supersedes the single-fixed-venue model from the previous migration.
-- Everything here is reachable only via the seating-chart-api edge
-- function's service-role client — none of these functions are granted
-- to anon/authenticated, so PIN brute-forcing can't bypass the worker's
-- rate limiting by hitting PostgREST directly.

alter table public.seating_chart_venues
    add column if not exists hashed_pin text;

-- Tracks PIN validation attempts per (slug, hashed client IP) so a
-- 4-digit PIN (10,000 possibilities) can't be brute-forced. Mirrors the
-- window/limit upstream Seating-Planner used (10 attempts / 15 minutes).
create table if not exists public.seating_chart_pin_attempts (
    id bigint generated by default as identity primary key,
    slug text not null,
    ip_hash text not null,
    attempted_at timestamptz not null default timezone('utc', now())
);

create index if not exists seating_chart_pin_attempts_lookup_idx
    on public.seating_chart_pin_attempts (slug, ip_hash, attempted_at);

alter table public.seating_chart_pin_attempts enable row level security;
revoke all on public.seating_chart_pin_attempts from anon, authenticated;

-- Records an attempt and raises if this (slug, ip) pair has hit the
-- rate limit. Called by seating_chart_check_pin before every comparison.
create or replace function public.seating_chart_record_pin_attempt(
    target_slug text,
    client_ip text
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    hashed_ip text := encode(digest(coalesce(client_ip, 'unknown'), 'sha256'), 'hex');
    recent_attempts integer;
begin
    delete from public.seating_chart_pin_attempts
    where attempted_at <= timezone('utc', now()) - interval '15 minutes';

    select count(*)
    into recent_attempts
    from public.seating_chart_pin_attempts
    where slug = target_slug
      and ip_hash = hashed_ip
      and attempted_at > timezone('utc', now()) - interval '15 minutes';

    if recent_attempts >= 10 then
        raise exception 'Too many PIN attempts for this chart. Try again in a few minutes.';
    end if;

    insert into public.seating_chart_pin_attempts (slug, ip_hash)
    values (target_slug, hashed_ip);
end;
$$;

-- Shared by validate-pin and save-with-pin so brute-forcing via either
-- path counts against the same rate limit.
create or replace function public.seating_chart_check_pin(
    target_slug text,
    candidate_pin text,
    client_ip text default null
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    stored_hash text;
begin
    perform public.seating_chart_record_pin_attempt(target_slug, client_ip);

    select hashed_pin into stored_hash
    from public.seating_chart_venues
    where slug = target_slug;

    if stored_hash is null or candidate_pin is null or candidate_pin = '' then
        return false;
    end if;

    return crypt(candidate_pin, stored_hash) = stored_hash;
end;
$$;

-- Admin-only: create a new venue with a caller-supplied slug (the worker
-- generates a human-friendly one, e.g. "warm-table-482", with retry on
-- collision) and an auto-generated 4-digit PIN, returned once in plaintext
-- so the admin can share it.
create or replace function public.seating_chart_create_venue(
    session_token text,
    slug text,
    event_title text default 'New Event'
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    generated_pin text;
begin
    perform public.require_session(session_token, 'admin');

    if trim(coalesce(slug, '')) = '' then
        raise exception 'slug is required.';
    end if;

    generated_pin := lpad(floor(random() * 10000)::int::text, 4, '0');

    insert into public.seating_chart_venues (slug, venue_data, hashed_pin)
    values (
        slug,
        jsonb_build_object(
            'shapes', '[]'::jsonb,
            'guests', '[]'::jsonb,
            'eventTitle', coalesce(nullif(trim(event_title), ''), 'New Event'),
            'tableCounter', 1
        ),
        crypt(generated_pin, gen_salt('bf'))
    );

    return jsonb_build_object('success', true, 'slug', slug, 'pin', generated_pin);
end;
$$;

-- Admin-only: list every venue (for the admin's venue picker).
create or replace function public.seating_chart_list_venues(session_token text)
returns jsonb
language sql
security definer
set search_path = public, extensions
as $$
    with authorized as (select public.require_session(session_token, 'admin'))
    select coalesce(jsonb_agg(jsonb_build_object(
        'slug', v.slug,
        'eventTitle', coalesce(v.venue_data->>'eventTitle', 'Untitled Event'),
        'updatedAt', v.updated_at,
        'hasPin', v.hashed_pin is not null
    ) order by v.updated_at desc), '[]'::jsonb)
    from public.seating_chart_venues v, authorized;
$$;

-- Public (no session required): fetch a venue by slug. This is what
-- makes a chart "shareable" — viewing never requires a password, only
-- editing does. Returns null if the slug doesn't exist.
create or replace function public.seating_chart_get_venue(target_slug text)
returns jsonb
language sql
security definer
set search_path = public, extensions
as $$
    select jsonb_build_object(
        'slug', v.slug,
        'venueData', v.venue_data,
        'updatedAt', v.updated_at,
        'hasPin', v.hashed_pin is not null
    )
    from public.seating_chart_venues v
    where v.slug = target_slug;
$$;

-- Save a venue's state. Allowed if session_token proves admin, OR
-- candidate_pin matches that venue's hashed_pin (rate-limited).
create or replace function public.seating_chart_save_venue(
    session_token text,
    target_slug text,
    new_venue_data jsonb,
    candidate_pin text default null,
    client_ip text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    is_admin boolean := false;
    updated timestamptz;
begin
    if session_token is not null and session_token <> '' then
        begin
            perform public.require_session(session_token, 'admin');
            is_admin := true;
        exception when others then
            is_admin := false;
        end;
    end if;

    if not is_admin then
        if candidate_pin is null or candidate_pin = '' then
            raise exception 'Unauthorized';
        end if;
        if not public.seating_chart_check_pin(target_slug, candidate_pin, client_ip) then
            raise exception 'Incorrect PIN.';
        end if;
    end if;

    update public.seating_chart_venues
    set venue_data = new_venue_data
    where slug = target_slug
    returning updated_at into updated;

    if updated is null then
        raise exception 'Chart not found.';
    end if;

    return jsonb_build_object('success', true, 'updatedAt', updated);
end;
$$;

-- Admin-only: set or regenerate a venue's PIN. Returns the new PIN once,
-- in plaintext, so the admin can re-share it.
create or replace function public.seating_chart_set_pin(
    session_token text,
    target_slug text,
    new_pin text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    resolved_pin text;
    updated timestamptz;
begin
    perform public.require_session(session_token, 'admin');

    resolved_pin := nullif(trim(coalesce(new_pin, '')), '');
    if resolved_pin is null then
        resolved_pin := lpad(floor(random() * 10000)::int::text, 4, '0');
    elsif resolved_pin !~ '^\d{4}$' then
        raise exception 'PIN must be a 4-digit number.';
    end if;

    update public.seating_chart_venues
    set hashed_pin = crypt(resolved_pin, gen_salt('bf'))
    where slug = target_slug
    returning updated_at into updated;

    if updated is null then
        raise exception 'Chart not found.';
    end if;

    return jsonb_build_object('success', true, 'pin', resolved_pin);
end;
$$;

-- Public (no session required), but rate-limited via seating_chart_check_pin:
-- lets a link recipient unlock edit mode by entering the venue's PIN.
create or replace function public.seating_chart_validate_pin(
    target_slug text,
    candidate_pin text,
    client_ip text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
    return jsonb_build_object(
        'success',
        public.seating_chart_check_pin(target_slug, candidate_pin, client_ip)
    );
end;
$$;
